services:
  vbc_liveqa:
    build: .
    platform: linux/amd64
    ports:
      - "4000:4000" # Map port 4000 on the host to port 4000 in the container
    volumes:
      - liveqa_data:/app/database
    environment:
      - MODERATOR_PASSWORD=mod123 # Pass environment

volumes:
  liveqa_data:
