version: '3.8'

services:
  VBC_LiveQA:
    image: optionull/liveqa:latest # Replace with your Docker Hub repository
    platform: linux/amd64
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - /DATA/AppData/VBC_LiveQA/LiveQA_AppData:/app # Mount the current directory into the container
      - /DATA/AppData/VBC_LiveQA/LiveQA_DB/questions.db:/app/questions.db # Persist the SQLite database
    environment:
      - MODERATOR_PASSWORD=mod123 # Pass environment